from django.contrib import admin
from .models import *

admin.site.register(AcademicSchoolYear)
admin.site.register(MyUser)
admin.site.register(AcademicSchoolYearType)
admin.site.register(AcademicSemester)
admin.site.register(AcademicSemesterPeriod)
admin.site.register(AcademicSemesterType)
admin.site.register(Class)
admin.site.register(ClassBillingItems)
admin.site.register(Currency)
admin.site.register(ClassType)
admin.site.register(Faculty)
admin.site.register(FacultyType)
admin.site.register(FamilyMember)
admin.site.register(FamilyMemberType)
admin.site.register(GenderTypes)
admin.site.register(Image)
admin.site.register(MaritalStatusType)
admin.site.register(InstallmentType)
admin.site.register(Parent)
admin.site.register(PeriodType)
admin.site.register(School)
admin.site.register(Student)
admin.site.register(StudentClass)
admin.site.register(StudentGrade)
admin.site.register(Subject)
admin.site.register(NationalityType)
